### ISSUE TITLE
Performance impact from importing all posts (n = a few hundred articles) and splicing selectively?

### ISSUE THREAD

**Issue by Ashvith10** [sharu725/yuyutsu#12]
I was wondering what the performance impact would be, if all the markdown files were imported and spliced? Is that part of the code optimized to handle a large number of post?

**Comment by sharu725** [comment]
This is right. A better way would be to import only required posts. I will think about it.

**Comment by Ashvith10** [comment]
@sharu725 Is pre-rendered pagination possible in SvelteKit using mdsvex? How about using `export const prerender = true;` in **+layout.js/+layout.server.js/+server.js**? That will effectively turn SvelteKit into a SSG, right?
