### ISSUE TITLE
The #tags link does not work correctly.

### ISSUE THREAD

**Issue by teteou** [sharu725/yuyutsu#8]
When you first access a tag, for example nature, the posts with that tag are listed correctly, but when you try to enter another tag from that position it doesn't work.

**Comment by teteou** [comment]
> 

It could be interesting to add a multiple selection of these categories. And add a button to delete those sections.

**Comment by sharu725** [comment]
> > 
> 
> It could be interesting to add a multiple selection of these categories. And add a button to delete those sections.

I didn't quite get this. Can you elaborate?

**Comment by teteou** [comment]
Nice job 🤝
