### ISSUE TITLE
Pagination homepage

### ISSUE THREAD

**Issue by teteou** [sharu725/yuyutsu#9]
Previously I remember that the possibility to paginate the content was implemented. I see that part of that pagination is still in -> pagination.svelte. I have tried to re-enable that feature, but I am unable to. I'm fairly new to Svelte and I'm using your project to learn. 

How can I re-paginate the homepage?

**Comment by sharu725** [comment]
Thanks @teteou. This is added back!

**Comment by teteou** [comment]
I think something is wrong with the pagination, as you can see on the second page it only adds the most recent post and not the ones that would go on the second page. I have tried adding more posts or changing the number of spots per page but it does not work correctly.
